### ISSUE TITLE
Game UI: Create view of opponents on the playing field

### ISSUE THREAD

**Issue by martinfri144** [lechld/Wizard#7]
Cards of the opponent will be rendered inside `RecyclerView` I guess. We could also manually populate the cards and add it to some container view. But I guess as we plan to use `RecyclerView` heavily inside the project we can rely on using it here too.
Above the opponent we need some other view to render at least the opponents name. A simple `TextView` should be fine for the start.
Let's render just one opponent in the first step. Once that works we can think how we switch the opponent in UI once next opponents turn starts.

**Comment by Kirschzelle** [comment]
Don't think this is reasonable with how little space we have on a standard phone. (could be reasonable for tablets, but we do not have the extra resources to work on an additional version for that.)

**Comment by Kirschzelle** [comment]
closing this and taking it off sprint
