### ISSUE TITLE
Build scoreboard, lobby and main view

### ISSUE THREAD

**Issue by martinfri144** [lechld/Wizard#8]
- [ ] Scoreboard - Martin
- [ ] Lobby - Ena
- [ ] Main - Claudia

**Comment by lechld** [comment]
I'd use `RecyclerView` for the all the screens. It has the sideeffect that it behaves on small screens well. Also we will need to use `RecyclerView` for https://github.com/lechld/Wizard/issues/7 and https://github.com/lechld/Wizard/issues/5. So getting some knowledge how that works in general is quite nice.

Let every screen be a `Fragment` with a custom `ViewModel` implementation. Real data will not be available before https://github.com/lechld/Wizard/issues/4, so let's just use dummy data to implement basic screen UI. That dummy data can then be easily replaced by real data.

**Comment by lechld** [comment]
I spliced it into separate issues
