### ISSUE TITLE
Create basic graphics for the game

### ISSUE THREAD

**Issue by martinfri144** [lechld/Wizard#9]
- [x] #35
- [x] #34

**Comment by lechld** [comment]
For cards we need:
* Wizard
* Jester
* The 4 colours
* Background

Let's try to generate something with an AI tool. 

If that doesn't work we need to define another Plan. Let's write down our conclusion here.

**Comment by Kirschzelle** [comment]
we already tried to create something with ai, looks promising, not a high priority right now though so no further testing was done

**Comment by Kirschzelle** [comment]
Artwork for cards is done, implementation blocked until #5 is done. Because of that this issue will have to be delayed.
